stages:
  - setup
  - test
  - upload
  - cleanup
  - upgrade

clone:
  stage: setup
  script:
    - cd
    - git clone http://gitlab.namibsun.net/namboy94/media-manager.git
    - git clone git@gitlab.namibsun.net:namboy94/media-manager.wiki.git

uninstall:
  stage: setup
  script:
    - sudo pip3.5 uninstall media_manager

run_unit_tests:
  stage: test
  script:
    - cd
    - cd media-manager
    - python setup.py test

generate_statistics:
  stage: test
  script:
    - cd
    - cd media-manager
    - git_stats generate

generate_documentation:
  stage: test
  script:
    - cd
    - cd media-manager/doc
    - make clean
    - make buildsource
    - make html
    - cd
    - cd media-manager.wiki
    - rm -rf html
    - cp -r ../media-manager/doc/build/html .
    - git add --all
    - git commit -m "updated documentation"

upload_to_pypi:
  stage: upload
  script:
    - cd
    - cd media-manager
    - python setup.py register sdist upload
    - sleep 60
  allow_failure: true

upload_statistics:
  stage: upload
  script:
    - cd
    - cd media-manager
    - rsync -avP --delete-after git_stats/ www.krumreyh.de@ssh.strato.de:~/git_stats_pages/media-manager
    - ssh www.krumreyh.de@ssh.strato.de 'rsync -av --delete-after git_stats_pages Homepage/'

upload_documentation:
  stage: upload
  script:
    - cd
    - cd media-manager.wiki
    - git push -u origin master

delete_clone:
  stage: cleanup
  when: always
  script:
    - cd
    - rm -rf media-manager
    - rm -rf media-manager.wiki

upgrade_from_pypi:
  stage: upgrade
  when: always
  script:
    - sudo pip3.5 install media_manager --upgrade
    - sleep 5
