stages:
  - mirror
  - test
  - build
  - deploy
  - release
  - docstats

variables:
  GITLAB_ACCESS_TOKEN: "$GITLAB_ACCESS_TOKEN"
  GITHUB_OAUTH_TOKEN: "$GITHUB_OAUTH_TOKEN"

clone_master:
  stage: mirror
  only:
    - master
    - develop
  tags:
    - key_github
  script:
    - git checkout master
    - git pull origin master
    - git push -u git@github.com:namboy94/toktokkie.git master --force
    - git checkout develop
    - git pull origin develop
    - git push -u git@github.com:namboy94/toktokkie.git develop --force

run_unit_tests_python_2:
  stage: test
  tags:
    - linux
    - python
  script:
    - 3to2 . --write
    - python2 setup.py test

run_unit_tests_python_3:
  stage: test
  tags:
    - linux
    - python
  script:
    - python3 setup.py nosetests --with-coverage --cover-package=toktokkie --cover-branches --cover-erase --cover-html --cover-inclusive
    - rsync -av cover/ /var/www/coverage.namibsun.net/public_html/toktokkie --delete-before
    - python3 builder.py coverage-html /var/www/coverage.namibsun.net/public_html

pyinstaller_linux:
  stage: build
  only:
    - master
  tags:
    - linux
    - python
  script:
    - python3 setup.py install --user
    - python3 builder.py build pyinstaller_linux
    - pip3 uninstall toktokkie -y
  artifacts:
    paths:
      - build/gitlab_build_scripts/*

#pyinstaller_windows:
#  stage: build
#  only:
#    - master
#  tags:
#    - windows
#    - python
#  script:
#    - python setup.py install
#    - python builder.py build pyinstaller_windows
#    - pip uninstall toktokkie -y
#  artifacts:
#    paths:
#      - build/gitlab_build_scripts/*

source_dist:
  stage: deploy
  only:
    - master
  tags:
    - linux
    - python
  script:
    - python3 setup.py register sdist upload

binary_3_dist:
  stage: deploy
  only:
    - master
  tags:
    - linux
    - python
  script:
    - python3 setup.py bdist_wheel upload

binary_2_dist:
  stage: deploy
  only:
    - master
  tags:
    - python
    - linux
  script:
    - 3to2 . --write
    - python2 setup.py bdist_wheel
    - twine upload dist/*

upload_release_to_github:
  stage: release
  only:
    - master
  tags:
    - linux
    - python
  script:
    - python3 builder.py github-release

upload_release_to_gitlab:
  stage: release
  only:
    - master
  tags:
    - linux
    - python
  script:
    - python3 builder.py gitlab-release

generate_sphinx_documentation:
  stage: docstats
  only:
    - master
    - develop
  tags:
    - linux
    - python
  script:
    - cd doc
    - make buildsource
    - make latexpdf
    - make html
    - rsync -av build/latex/toktokkie.pdf /var/www/docs.namibsun.net/public_html/pdf_docs/toktokkie.pdf --delete-before
    - rsync -av build/html/ /var/www/docs.namibsun.net/public_html/html_docs/toktokkie --delete-before
    - cd ..
    - python3 builder.py documentation-html /var/www/docs.namibsun.net/public_html
  artifacts:
    paths:
      - doc/build/latex/toktokkie.pdf
      - doc/build/html

gitstats:
  stage: docstats
  only:
    - master
    - develop
  tags:
    - linux
  script:
    - gitstats . gitstats
    - rsync -av gitstats/ /var/www/gitstats.namibsun.net/public_html/gitstats/toktokkie --delete-before
    - git_stats generate
    - rsync -av git_stats/ /var/www/gitstats.namibsun.net/public_html/git_stats/toktokkie --delete-before
    - python3 builder.py gitstats-html /var/www/gitstats.namibsun.net/public_html
  artifacts:
    paths:
      - gitstats
      - git_stats
