stages:
  - mirror
  - test
  - deploy
  - release
  - docs

github_mirror:
  stage: mirror
  tags:
    - github_namboy94_push
  script:
    - git checkout master
    - git pull
    - git push git@github.com:namboy94/toktokkie.git master -f
    - git checkout develop
    - git pull
    - git push git@github.com:namboy94/toktokkie.git develop -f

stylecheck:
  stage: test
  tags:
    - pycodestyle
  script:
    - pycodestyle .

run_unit_tests_python_2:
  stage: test
  tags:
    - python2
    - 3to2
  script:
    - 3to2 . --write
    - python2 setup.py test

run_unit_tests_python_3_with_coverage:
  stage: test
  tags:
    - python3
  script:
    - python3 setup.py nosetests -v
      --with-coverage --cover-package=toktokkie --cover-branches --cover-erase --cover-html --cover-inclusive
    - rsync -av cover/ /var/www/coverage.namibsun.net/public_html/toktokkie --delete-before

pypi_dist:
  stage: deploy
  only:
    - master
  tags:
    - python2
    - python3
    - pypi
  script:
    - python3 setup.py register sdist upload
    - python3 setup.py bdist_wheel upload
    - 3to2 . --write
    - rm -rf dist
    - python2 setup.py bdist_wheel
    - twine upload dist/*

upload_release_to_github:
  stage: release
  only:
    - master
  tags:
    - python
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/ci-scripts.git
    - python ci-scripts/src/changelog-reader/changelog-reader.py -c CHANGELOG -d current_changelog
    - python ci-scripts/src/github-release-uploader/github-release-uploader.py namboy94 toktokkie $GITHUB_ACCESS_TOKEN
      $(python3 setup.py -V) current_changelog artifacts -b master

upload_release_to_gitlab:
  stage: release
  only:
    - master
  tags:
    - python
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/ci-scripts.git
    - python ci-scripts/src/changelog-reader/changelog-reader.py -c CHANGELOG -d  current_changelog
    - python ci-scripts/src/gitlab-release-uploader/gitlab-release-uploader.py namboy94 toktokkie $GITLAB_ACCESS_TOKEN
      $(python3 setup.py -V) current_changelog artifacts -b master -u https://gitlab.namibsun.net

generate_sphinx_documentation:
  stage: docs
  only:
    - master
    - develop
  tags:
    - sphinx
    - latex
    - docs
  script:
    - cd doc
    - make buildsource
    - make latexpdf
    - make html
    - rsync -av build/latex/toktokkie.pdf
      /var/www/docs.namibsun.net/public_html/pdf_docs/toktokkie.pdf --delete-before
    - rsync -av build/html/ /var/www/docs.namibsun.net/public_html/html_docs/toktokkie --delete-before
    - cd ..
