stages:
  - setup
  - test
  - deploy
  - wiki

clone_master:
  stage: setup
  only:
    - master
    - develop
  script:
    #- git push -u git@gitlab.com:namboy94/media-manager.git master
    - git push -u git@github.com:namboy94/media-manager.git master
    #- git push -u git@github.com:namboy94/media-manager.git develop
    #- git push -u git@bitbucket.org:namboy94/media-manager.git master

run_unit_tests:
  stage: test
  only:
    - master
    - develop
  script:
    - python3 setup.py test


#upload_python2_version:
#  stage: deploy
#  only:
#    - master
#  script:
#    - 3to2 --write .
#    - rm setup.py
#    - mv setup2.py setup.py
#    - python2 setup.py register sdist upload
#  allow_failure: true

upload_to_pypi:
  stage: deploy
  only:
    - master
  script:
    - python3 setup.py register sdist upload
  allow_failure: true

upload_documentation_and_statistics:
  stage: wiki
  only:
    - master
    - develop
  script:
    - gitstats . git_stats
    - cd doc
    - make clean
    - make buildsource
    - make html
    - cd ..

    - git clone git@gitlab.namibsun.net:namboy94/messengerbot.wiki.git
    - cd messengerbot.wiki
    - rm -rf git_stats html
    - mv ../git_stats .
    - mv ../doc/build/html .