# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toktokkie/ui/qt/qt_designer/metadata_configurator.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MetadataConfigurator(object):
    def setupUi(self, MetadataConfigurator):
        MetadataConfigurator.setObjectName("MetadataConfigurator")
        MetadataConfigurator.resize(901, 585)
        self.centralwidget = QtWidgets.QWidget(MetadataConfigurator)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_stack = QtWidgets.QStackedWidget(self.centralwidget)
        self.widget_stack.setEnabled(True)
        self.widget_stack.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.widget_stack.setObjectName("widget_stack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget_stack.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.widget_stack.addWidget(self.page_2)
        self.gridLayout.addWidget(self.widget_stack, 1, 3, 3, 1)
        self.media_tree = QtWidgets.QTreeWidget(self.centralwidget)
        self.media_tree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.media_tree.setAcceptDrops(False)
        self.media_tree.setObjectName("media_tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.media_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.media_tree)
        self.gridLayout.addWidget(self.media_tree, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_new_button = QtWidgets.QPushButton(self.frame)
        self.add_new_button.setObjectName("add_new_button")
        self.gridLayout_2.addWidget(self.add_new_button, 1, 0, 1, 1)
        self.add_new_edit = QtWidgets.QLineEdit(self.frame)
        self.add_new_edit.setObjectName("add_new_edit")
        self.gridLayout_2.addWidget(self.add_new_edit, 1, 1, 1, 1)
        self.browse_button = QtWidgets.QPushButton(self.frame)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout_2.addWidget(self.browse_button, 1, 2, 1, 1)
        self.remove_button = QtWidgets.QPushButton(self.frame)
        self.remove_button.setObjectName("remove_button")
        self.gridLayout_2.addWidget(self.remove_button, 2, 0, 1, 3)
        self.media_directory_list = QtWidgets.QTreeWidget(self.frame)
        self.media_directory_list.setMaximumSize(QtCore.QSize(16777215, 75))
        self.media_directory_list.setObjectName("media_directory_list")
        item_0 = QtWidgets.QTreeWidgetItem(self.media_directory_list)
        item_0 = QtWidgets.QTreeWidgetItem(self.media_directory_list)
        self.gridLayout_2.addWidget(self.media_directory_list, 0, 0, 1, 3)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1)
        MetadataConfigurator.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MetadataConfigurator)
        self.statusbar.setObjectName("statusbar")
        MetadataConfigurator.setStatusBar(self.statusbar)

        self.retranslateUi(MetadataConfigurator)
        self.widget_stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MetadataConfigurator)

    def retranslateUi(self, MetadataConfigurator):
        _translate = QtCore.QCoreApplication.translate
        MetadataConfigurator.setWindowTitle(_translate("MetadataConfigurator", "MainWindow"))
        self.media_tree.headerItem().setText(0, _translate("MetadataConfigurator", "Media"))
        __sortingEnabled = self.media_tree.isSortingEnabled()
        self.media_tree.setSortingEnabled(False)
        self.media_tree.topLevelItem(0).setText(0, _translate("MetadataConfigurator", "One"))
        self.media_tree.topLevelItem(0).child(0).setText(0, _translate("MetadataConfigurator", "Two"))
        self.media_tree.topLevelItem(1).setText(0, _translate("MetadataConfigurator", "Three"))
        self.media_tree.setSortingEnabled(__sortingEnabled)
        self.add_new_button.setText(_translate("MetadataConfigurator", "Add New"))
        self.browse_button.setText(_translate("MetadataConfigurator", "Browse"))
        self.remove_button.setText(_translate("MetadataConfigurator", "Remove"))
        self.media_directory_list.headerItem().setText(0, _translate("MetadataConfigurator", "Source Directories"))
        __sortingEnabled = self.media_directory_list.isSortingEnabled()
        self.media_directory_list.setSortingEnabled(False)
        self.media_directory_list.topLevelItem(0).setText(0, _translate("MetadataConfigurator", "A"))
        self.media_directory_list.topLevelItem(1).setText(0, _translate("MetadataConfigurator", "B"))
        self.media_directory_list.setSortingEnabled(__sortingEnabled)

