# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toktokkie/ui/qt/qt_designer/tv_series_config.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TvSeriesConfig(object):
    def setupUi(self, TvSeriesConfig):
        TvSeriesConfig.setObjectName("TvSeriesConfig")
        TvSeriesConfig.resize(973, 579)
        self.gridLayout = QtWidgets.QGridLayout(TvSeriesConfig)
        self.gridLayout.setObjectName("gridLayout")
        self.series_name_edit = QtWidgets.QLineEdit(TvSeriesConfig)
        self.series_name_edit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.series_name_edit.sizePolicy().hasHeightForWidth())
        self.series_name_edit.setSizePolicy(sizePolicy)
        self.series_name_edit.setMinimumSize(QtCore.QSize(134, 0))
        self.series_name_edit.setFrame(False)
        self.series_name_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.series_name_edit.setObjectName("series_name_edit")
        self.gridLayout.addWidget(self.series_name_edit, 1, 0, 1, 1)
        self.folder_icon_label = QtWidgets.QLabel(TvSeriesConfig)
        self.folder_icon_label.setMaximumSize(QtCore.QSize(512, 512))
        self.folder_icon_label.setText("")
        self.folder_icon_label.setPixmap(QtGui.QPixmap("../../../../../../../Downloads/pokemon_folder_icon_by_mikromike-d8mldi8.png"))
        self.folder_icon_label.setScaledContents(True)
        self.folder_icon_label.setObjectName("folder_icon_label")
        self.gridLayout.addWidget(self.folder_icon_label, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(TvSeriesConfig)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.confirm_changes_button = QtWidgets.QPushButton(self.frame)
        self.confirm_changes_button.setObjectName("confirm_changes_button")
        self.gridLayout_2.addWidget(self.confirm_changes_button, 10, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.amount_of_episodes_label = QtWidgets.QLabel(self.frame_2)
        self.amount_of_episodes_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.amount_of_episodes_label.setAlignment(QtCore.Qt.AlignCenter)
        self.amount_of_episodes_label.setObjectName("amount_of_episodes_label")
        self.gridLayout_3.addWidget(self.amount_of_episodes_label, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.genres_label = QtWidgets.QLabel(self.frame_2)
        self.genres_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.genres_label.setAlignment(QtCore.Qt.AlignCenter)
        self.genres_label.setWordWrap(True)
        self.genres_label.setObjectName("genres_label")
        self.gridLayout_3.addWidget(self.genres_label, 5, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 5, 0, 1, 1)
        self.amount_of_seasons_label = QtWidgets.QLabel(self.frame_2)
        self.amount_of_seasons_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.amount_of_seasons_label.setAlignment(QtCore.Qt.AlignCenter)
        self.amount_of_seasons_label.setObjectName("amount_of_seasons_label")
        self.gridLayout_3.addWidget(self.amount_of_seasons_label, 4, 1, 1, 1)
        self.first_aired_label = QtWidgets.QLabel(self.frame_2)
        self.first_aired_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.first_aired_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_aired_label.setObjectName("first_aired_label")
        self.gridLayout_3.addWidget(self.first_aired_label, 1, 1, 1, 1)
        self.episode_length_label = QtWidgets.QLabel(self.frame_2)
        self.episode_length_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.episode_length_label.setAlignment(QtCore.Qt.AlignCenter)
        self.episode_length_label.setObjectName("episode_length_label")
        self.gridLayout_3.addWidget(self.episode_length_label, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 9, 0, 1, 3)
        self.resolution_three_edit_y = QtWidgets.QLineEdit(self.frame)
        self.resolution_three_edit_y.setObjectName("resolution_three_edit_y")
        self.gridLayout_2.addWidget(self.resolution_three_edit_y, 5, 2, 1, 1)
        self.tags_edit = QtWidgets.QLineEdit(self.frame)
        self.tags_edit.setObjectName("tags_edit")
        self.gridLayout_2.addWidget(self.tags_edit, 1, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.audio_language_edit = QtWidgets.QLineEdit(self.frame)
        self.audio_language_edit.setObjectName("audio_language_edit")
        self.gridLayout_2.addWidget(self.audio_language_edit, 6, 1, 1, 2)
        self.resolution_one_edit_x = QtWidgets.QLineEdit(self.frame)
        self.resolution_one_edit_x.setObjectName("resolution_one_edit_x")
        self.gridLayout_2.addWidget(self.resolution_one_edit_x, 3, 1, 1, 1)
        self.resolution_three_edit_x = QtWidgets.QLineEdit(self.frame)
        self.resolution_three_edit_x.setObjectName("resolution_three_edit_x")
        self.gridLayout_2.addWidget(self.resolution_three_edit_x, 5, 1, 1, 1)
        self.tvdb_url_edit = QtWidgets.QLineEdit(self.frame)
        self.tvdb_url_edit.setObjectName("tvdb_url_edit")
        self.gridLayout_2.addWidget(self.tvdb_url_edit, 2, 1, 1, 1)
        self.resolution_one_edit_y = QtWidgets.QLineEdit(self.frame)
        self.resolution_one_edit_y.setObjectName("resolution_one_edit_y")
        self.gridLayout_2.addWidget(self.resolution_one_edit_y, 3, 2, 1, 1)
        self.resolution_two_edit_y = QtWidgets.QLineEdit(self.frame)
        self.resolution_two_edit_y.setObjectName("resolution_two_edit_y")
        self.gridLayout_2.addWidget(self.resolution_two_edit_y, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.media_type_combo_box = QtWidgets.QComboBox(self.frame)
        self.media_type_combo_box.setObjectName("media_type_combo_box")
        self.media_type_combo_box.addItem("")
        self.gridLayout_2.addWidget(self.media_type_combo_box, 0, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 3, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.subtitle_language_edit = QtWidgets.QLineEdit(self.frame)
        self.subtitle_language_edit.setObjectName("subtitle_language_edit")
        self.gridLayout_2.addWidget(self.subtitle_language_edit, 7, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 7, 0, 1, 1)
        self.resolution_two_edit_x = QtWidgets.QLineEdit(self.frame)
        self.resolution_two_edit_x.setObjectName("resolution_two_edit_x")
        self.gridLayout_2.addWidget(self.resolution_two_edit_x, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 8, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 5, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 0, 1, 1)

        self.retranslateUi(TvSeriesConfig)
        QtCore.QMetaObject.connectSlotsByName(TvSeriesConfig)

    def retranslateUi(self, TvSeriesConfig):
        _translate = QtCore.QCoreApplication.translate
        TvSeriesConfig.setWindowTitle(_translate("TvSeriesConfig", "Form"))
        self.series_name_edit.setText(_translate("TvSeriesConfig", "Series Name"))
        self.confirm_changes_button.setText(_translate("TvSeriesConfig", "Confirm Changes"))
        self.amount_of_episodes_label.setText(_translate("TvSeriesConfig", "100"))
        self.label_10.setText(_translate("TvSeriesConfig", "Episode Runtime"))
        self.label_12.setText(_translate("TvSeriesConfig", "Amount of Episodes"))
        self.label_8.setText(_translate("TvSeriesConfig", "First Aired"))
        self.genres_label.setText(_translate("TvSeriesConfig", "Genre1, Genre2, Genre3, genre4, Genre5, Genre6, Genre7"))
        self.label_16.setText(_translate("TvSeriesConfig", "Genres"))
        self.amount_of_seasons_label.setText(_translate("TvSeriesConfig", "10"))
        self.first_aired_label.setText(_translate("TvSeriesConfig", "September 24, 2007"))
        self.episode_length_label.setText(_translate("TvSeriesConfig", "25 Minutes"))
        self.label_14.setText(_translate("TvSeriesConfig", "Amount of Seasons"))
        self.resolution_three_edit_y.setText(_translate("TvSeriesConfig", "480"))
        self.tags_edit.setText(_translate("TvSeriesConfig", "tag1, tag2"))
        self.label_6.setText(_translate("TvSeriesConfig", "Audio Languages"))
        self.audio_language_edit.setText(_translate("TvSeriesConfig", "ENG,JAP"))
        self.resolution_one_edit_x.setText(_translate("TvSeriesConfig", "1920"))
        self.resolution_three_edit_x.setText(_translate("TvSeriesConfig", "720"))
        self.tvdb_url_edit.setText(_translate("TvSeriesConfig", "TVDB URL"))
        self.resolution_one_edit_y.setText(_translate("TvSeriesConfig", "1080"))
        self.resolution_two_edit_y.setText(_translate("TvSeriesConfig", "720"))
        self.label_2.setText(_translate("TvSeriesConfig", "TheTVDB.com"))
        self.media_type_combo_box.setItemText(0, _translate("TvSeriesConfig", "TV Series"))
        self.label_5.setText(_translate("TvSeriesConfig", "Resolutions"))
        self.pushButton.setText(_translate("TvSeriesConfig", "PushButton"))
        self.label_3.setText(_translate("TvSeriesConfig", "Tags"))
        self.label_4.setText(_translate("TvSeriesConfig", "Media Type"))
        self.subtitle_language_edit.setText(_translate("TvSeriesConfig", "ENG,JAP"))
        self.label_7.setText(_translate("TvSeriesConfig", "Subtitle Languages"))
        self.resolution_two_edit_x.setText(_translate("TvSeriesConfig", "1280"))

