# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toktokkie/ui/qt/qt_designer/xdcc_download_manager.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_XDCCDownloadManagerWindow(object):
    def setupUi(self, XDCCDownloadManagerWindow):
        XDCCDownloadManagerWindow.setObjectName("XDCCDownloadManagerWindow")
        XDCCDownloadManagerWindow.resize(970, 561)
        self.centralwidget = QtWidgets.QWidget(XDCCDownloadManagerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setObjectName("search_button")
        self.gridLayout.addWidget(self.search_button, 11, 4, 1, 1)
        self.main_icon_browser = QtWidgets.QPushButton(self.centralwidget)
        self.main_icon_browser.setObjectName("main_icon_browser")
        self.gridLayout.addWidget(self.main_icon_browser, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 11, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        self.search_result_list = QtWidgets.QTreeWidget(self.centralwidget)
        self.search_result_list.setMinimumSize(QtCore.QSize(512, 300))
        self.search_result_list.setObjectName("search_result_list")
        self.gridLayout.addWidget(self.search_result_list, 8, 0, 3, 5)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 8, 7, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem1, 4, 4, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 3, 4, 1, 1)
        self.season_icon_browser = QtWidgets.QPushButton(self.centralwidget)
        self.season_icon_browser.setObjectName("season_icon_browser")
        self.gridLayout.addWidget(self.season_icon_browser, 6, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 9, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(278, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 3, 1, 1, 1)
        self.directory_browser = QtWidgets.QPushButton(self.centralwidget)
        self.directory_browser.setObjectName("directory_browser")
        self.gridLayout.addWidget(self.directory_browser, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 3, 1, 1)
        self.directory_field = QtWidgets.QTextEdit(self.centralwidget)
        self.directory_field.setMaximumSize(QtCore.QSize(16777215, 30))
        self.directory_field.setObjectName("directory_field")
        self.gridLayout.addWidget(self.directory_field, 0, 2, 1, 4)
        self.search_term_field = QtWidgets.QTextEdit(self.centralwidget)
        self.search_term_field.setMaximumSize(QtCore.QSize(16777215, 30))
        self.search_term_field.setObjectName("search_term_field")
        self.gridLayout.addWidget(self.search_term_field, 11, 1, 1, 3)
        self.show_name_field = QtWidgets.QTextEdit(self.centralwidget)
        self.show_name_field.setMaximumSize(QtCore.QSize(16777215, 30))
        self.show_name_field.setObjectName("show_name_field")
        self.gridLayout.addWidget(self.show_name_field, 2, 1, 1, 5)
        self.auto_rename_check = QtWidgets.QCheckBox(self.centralwidget)
        self.auto_rename_check.setObjectName("auto_rename_check")
        self.gridLayout.addWidget(self.auto_rename_check, 10, 7, 1, 1)
        self.main_icon_field = QtWidgets.QTextEdit(self.centralwidget)
        self.main_icon_field.setMaximumSize(QtCore.QSize(16777215, 30))
        self.main_icon_field.setObjectName("main_icon_field")
        self.gridLayout.addWidget(self.main_icon_field, 5, 2, 1, 4)
        self.season_icon_field = QtWidgets.QTextEdit(self.centralwidget)
        self.season_icon_field.setMaximumSize(QtCore.QSize(16777215, 30))
        self.season_icon_field.setObjectName("season_icon_field")
        self.gridLayout.addWidget(self.season_icon_field, 6, 2, 1, 4)
        self.download_button = QtWidgets.QPushButton(self.centralwidget)
        self.download_button.setObjectName("download_button")
        self.gridLayout.addWidget(self.download_button, 11, 7, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber.setMinimumSize(QtCore.QSize(0, 40))
        self.lcdNumber.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_3.addWidget(self.lcdNumber, 4, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 3, 1, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(self.widget)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout_3.addWidget(self.progressBar_2, 2, 1, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_2.setMinimumSize(QtCore.QSize(0, 40))
        self.lcdNumber_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout_3.addWidget(self.lcdNumber_2, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 5, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 4, 2, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 7, 7, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 6, 7, 1)
        self.gridFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridFrame.sizePolicy().hasHeightForWidth())
        self.gridFrame.setSizePolicy(sizePolicy)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 3, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gridFrame, 8, 5, 1, 1)
        XDCCDownloadManagerWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(XDCCDownloadManagerWindow)
        self.statusbar.setObjectName("statusbar")
        XDCCDownloadManagerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(XDCCDownloadManagerWindow)
        QtCore.QMetaObject.connectSlotsByName(XDCCDownloadManagerWindow)

    def retranslateUi(self, XDCCDownloadManagerWindow):
        _translate = QtCore.QCoreApplication.translate
        XDCCDownloadManagerWindow.setWindowTitle(_translate("XDCCDownloadManagerWindow", "XDCC Download Manager"))
        self.search_button.setText(_translate("XDCCDownloadManagerWindow", "Search"))
        self.main_icon_browser.setText(_translate("XDCCDownloadManagerWindow", "Browse"))
        self.label_8.setText(_translate("XDCCDownloadManagerWindow", "Search Term"))
        self.label_5.setText(_translate("XDCCDownloadManagerWindow", "Season Icon"))
        self.label.setText(_translate("XDCCDownloadManagerWindow", "Target Directory"))
        self.label_4.setText(_translate("XDCCDownloadManagerWindow", "Main Icon"))
        self.label_2.setText(_translate("XDCCDownloadManagerWindow", "Show Name"))
        self.search_result_list.headerItem().setText(0, _translate("XDCCDownloadManagerWindow", "#"))
        self.search_result_list.headerItem().setText(1, _translate("XDCCDownloadManagerWindow", "Bot"))
        self.search_result_list.headerItem().setText(2, _translate("XDCCDownloadManagerWindow", "Pack"))
        self.search_result_list.headerItem().setText(3, _translate("XDCCDownloadManagerWindow", "Size"))
        self.search_result_list.headerItem().setText(4, _translate("XDCCDownloadManagerWindow", "Filename"))
        self.season_icon_browser.setText(_translate("XDCCDownloadManagerWindow", "Browse"))
        self.pushButton_4.setText(_translate("XDCCDownloadManagerWindow", "▲"))
        self.pushButton_5.setText(_translate("XDCCDownloadManagerWindow", "▼"))
        self.label_3.setText(_translate("XDCCDownloadManagerWindow", "Season Number"))
        self.directory_browser.setText(_translate("XDCCDownloadManagerWindow", "Browse"))
        self.label_7.setText(_translate("XDCCDownloadManagerWindow", "Episode Number"))
        self.auto_rename_check.setText(_translate("XDCCDownloadManagerWindow", "Auto-Rename"))
        self.download_button.setText(_translate("XDCCDownloadManagerWindow", "Download"))
        self.label_9.setText(_translate("XDCCDownloadManagerWindow", "Single Progress"))
        self.label_6.setText(_translate("XDCCDownloadManagerWindow", "Total Progress"))
        self.label_11.setText(_translate("XDCCDownloadManagerWindow", "Average Speed"))
        self.label_10.setText(_translate("XDCCDownloadManagerWindow", "Current Speed"))
        self.pushButton.setText(_translate("XDCCDownloadManagerWindow", "►"))
        self.pushButton_2.setText(_translate("XDCCDownloadManagerWindow", "◄"))

